[2025-03-14T17:41:19.967+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T17:41:19.978+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mtrix_produtos_edi.ingest_produtos_mtrix manual__2025-03-14T17:36:17.237184+00:00 [queued]>
[2025-03-14T17:41:19.982+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mtrix_produtos_edi.ingest_produtos_mtrix manual__2025-03-14T17:36:17.237184+00:00 [queued]>
[2025-03-14T17:41:19.982+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-14T17:41:19.989+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_produtos_mtrix> on 2025-03-14 17:36:17.237184+00:00
[2025-03-14T17:41:19.994+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T17:41:19.995+0000] {standard_task_runner.py:72} INFO - Started process 84 to run task
[2025-03-14T17:41:19.996+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mtrix_produtos_edi', 'ingest_produtos_mtrix', 'manual__2025-03-14T17:36:17.237184+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/mtrix_produtos_edi.py', '--cfg-path', '/tmp/tmpfr85ix9d']
[2025-03-14T17:41:19.998+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask ingest_produtos_mtrix
[2025-03-14T17:41:20.032+0000] {task_command.py:467} INFO - Running <TaskInstance: mtrix_produtos_edi.ingest_produtos_mtrix manual__2025-03-14T17:36:17.237184+00:00 [running]> on host 0e3fba95cc8e
[2025-03-14T17:41:20.088+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mtrix_produtos_edi' AIRFLOW_CTX_TASK_ID='ingest_produtos_mtrix' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T17:36:17.237184+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T17:36:17.237184+00:00'
[2025-03-14T17:41:20.089+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T17:41:20.118+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mtrix_produtos_edi.py", line 193, in ingest_produtos
    cur.execute(INSERT_QUERY, record_data)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)

[2025-03-14T17:41:20.125+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=mtrix_produtos_edi, task_id=ingest_produtos_mtrix, run_id=manual__2025-03-14T17:36:17.237184+00:00, execution_date=20250314T173617, start_date=20250314T174119, end_date=20250314T174120
[2025-03-14T17:41:20.142+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T17:41:20.142+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 61 for task ingest_produtos_mtrix (value too long for type character(1)
; 84)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mtrix_produtos_edi.py", line 193, in ingest_produtos
    cur.execute(INSERT_QUERY, record_data)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)

[2025-03-14T17:41:20.168+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-14T17:41:20.179+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T17:41:20.181+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
